//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int No { get; set; }
        public String Course { get; set; }
        public string FeedbackMessage { get; set; }
    }

    public enum SchoolCourse
    {
        Advanced_Computational_Science,
Component_Based_Architecture,
Development_Project,
Object_Oriented_Design_and_Development,
Real_Time_Dependable_System,
Trustworthy_Computing

    }
}
